name: scan_master
description: "A document scanning and AI chat application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.5.2
  
  # Camera and Image Processing (NEW)
  camera: ^0.10.6
  image: ^4.1.7
  path_provider: ^2.1.5
  path: ^1.9.1
  
  # File Handling
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  
  # Utilities
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  intl: ^0.20.2
  provider: ^6.1.5
  share_plus: ^11.0.0
  
  # Payment
  razorpay_flutter: ^1.4.0
  
  # Math and Vectors (NEW - for image transformations)
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets for camera overlay
  assets:
    - assets/images/
    - assets/icons/

  # Custom fonts (optional)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700