// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdx5j3FnrteWGy0zJAjbLGLYvVSn9mZX8',
    appId: '1:757169597458:web:b7963f20650885e3a0bccb',
    messagingSenderId: '757169597458',
    projectId: 'scan-master-app',
    authDomain: 'scan-master-app.firebaseapp.com',
    storageBucket: 'scan-master-app.firebasestorage.app',
    measurementId: 'G-QHRCDHDK1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ7Tj6isll4gKM-cr1AfK_vvUfB1JbVGw',
    appId: '1:757169597458:android:d3fb9c540c7516dca0bccb',
    messagingSenderId: '757169597458',
    projectId: 'scan-master-app',
    storageBucket: 'scan-master-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2obOJAu9mbo0DlmiaOV4N-BXwupO_Ad0',
    appId: '1:757169597458:ios:ad64cf1277865291a0bccb',
    messagingSenderId: '757169597458',
    projectId: 'scan-master-app',
    storageBucket: 'scan-master-app.firebasestorage.app',
    iosBundleId: 'com.example.scanMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2obOJAu9mbo0DlmiaOV4N-BXwupO_Ad0',
    appId: '1:757169597458:ios:ad64cf1277865291a0bccb',
    messagingSenderId: '757169597458',
    projectId: 'scan-master-app',
    storageBucket: 'scan-master-app.firebasestorage.app',
    iosBundleId: 'com.example.scanMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdx5j3FnrteWGy0zJAjbLGLYvVSn9mZX8',
    appId: '1:757169597458:web:4f833a0b9a2b8b83a0bccb',
    messagingSenderId: '757169597458',
    projectId: 'scan-master-app',
    authDomain: 'scan-master-app.firebaseapp.com',
    storageBucket: 'scan-master-app.firebasestorage.app',
    measurementId: 'G-RZCW9QFQ3M',
  );
}
