name: Deploy Backend Services (Multi-Region)

on:
  push:
    branches: [main]
    paths: ['backend/**']
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changes.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Detect changed services
        id: changes
        run: |
          services=()
          
          # Check each service for changes
          changed_services=()
          
          if git diff HEAD~1 --name-only | grep -q "backend/generate_doc_summary_service/"; then
            changed_services+=("generate_doc_summary_service")
          fi
          
          if git diff HEAD~1 --name-only | grep -q "backend/chat_service/"; then
            changed_services+=("chat_service")
          fi
          
          if git diff HEAD~1 --name-only | grep -q "backend/conversion_service/"; then
            changed_services+=("conversion_service")
          fi
          
          if git diff HEAD~1 --name-only | grep -q "backend/check_upload_allowance_service/"; then
            changed_services+=("check_upload_allowance_service")
          fi
          
          if git diff HEAD~1 --name-only | grep -q "backend/delete_file_service/"; then
            changed_services+=("delete_file_service")
          fi
          
          if git diff HEAD~1 --name-only | grep -q "backend/get_download_url_service/"; then
            changed_services+=("get_download_url_service")
          fi
          
          if git diff HEAD~1 --name-only | grep -q "backend/subscription_service/"; then
            changed_services+=("subscription_service")
          fi
          
          if git diff HEAD~1 --name-only | grep -q "backend/verify_payment_service/"; then
            changed_services+=("verify_payment_service")
          fi
          
          # Create matrix
          matrix="["
          first=true
          
          for service in "${changed_services[@]}"; do
            for region in "us-central1" "asia-south1" "europe-west1"; do
              if [ "$first" = true ]; then
                first=false
              else
                matrix+=","
              fi
              
              case "$service" in
                "generate_doc_summary_service")
                  matrix+="{\"service\":\"generate_doc_summary_service\",\"function_name\":\"generate-doc-summary\",\"entry_point\":\"generate_doc_summary\",\"service_account\":\"generate-doc-summary-sa@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com\",\"type\":\"function\",\"region\":\"$region\"}"
                  ;;
                "chat_service")
                  matrix+="{\"service\":\"chat_service\",\"function_name\":\"chat-with-document\",\"entry_point\":\"chat_with_document\",\"service_account\":\"chat-service-sa@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com\",\"type\":\"function\",\"region\":\"$region\"}"
                  ;;
                "conversion_service")
                  matrix+="{\"service\":\"conversion_service\",\"service_name\":\"document-converter\",\"service_account\":\"conversion-service-sa@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com\",\"type\":\"run\",\"region\":\"$region\"}"
                  ;;
                "check_upload_allowance_service")
                  matrix+="{\"service\":\"check_upload_allowance_service\",\"function_name\":\"check-upload-allowance\",\"entry_point\":\"check_upload_allowance\",\"service_account\":\"check-upload-allowance-sa@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com\",\"type\":\"function\",\"region\":\"$region\"}"
                  ;;
                "delete_file_service")
                  matrix+="{\"service\":\"delete_file_service\",\"function_name\":\"delete-file\",\"entry_point\":\"delete_file\",\"service_account\":\"delete-file-sa@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com\",\"type\":\"function\",\"region\":\"$region\"}"
                  ;;
                "get_download_url_service")
                  matrix+="{\"service\":\"get_download_url_service\",\"function_name\":\"get-download-url\",\"entry_point\":\"get_signed_url\",\"service_account\":\"get-download-url-sa@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com\",\"type\":\"function\",\"region\":\"$region\"}"
                  ;;
                "subscription_service")
                  matrix+="{\"service\":\"subscription_service\",\"function_name\":\"create-subscription-order\",\"entry_point\":\"create_subscription_order\",\"service_account\":\"subscription-service-sa@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com\",\"type\":\"function\",\"region\":\"$region\"}"
                  ;;
                "verify_payment_service")
                  matrix+="{\"service\":\"verify_payment_service\",\"function_name\":\"verify-payment\",\"entry_point\":\"verify_payment\",\"service_account\":\"verify-payment-sa@${{ secrets.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com\",\"type\":\"function\",\"region\":\"$region\"}"
                  ;;
              esac
            done
          done
          
          matrix+="]"
          
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "Matrix: $matrix"
          echo "Changed services: ${changed_services[*]}"
          
          # Handle empty matrix case
          if [ "$matrix" = "[]" ]; then
            echo "No backend services changed - skipping deployment"
          else
            echo "Matrix created successfully with ${#changed_services[@]} services"
          fi

  deploy:
    needs: detect-changes
    if: needs.detect-changes.outputs.matrix != '[]' && needs.detect-changes.outputs.matrix != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.detect-changes.outputs.matrix || '[]') }}
      max-parallel: 3
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Prepare service account key for signing services
        if: matrix.service == 'get_download_url_service'
        run: |
          echo '${{ secrets.GCLOUD_SA_KEY }}' > backend/get_download_url_service/service-account-key.json
      
      - name: Deploy Cloud Function
        if: matrix.type == 'function'
        run: |
          # Determine environment variables based on service
          ENV_VARS=""
          
          case "${{ matrix.service }}" in
            "subscription_service")
              ENV_VARS="--set-env-vars=RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}"
              ;;
            "verify_payment_service")
              ENV_VARS="--set-env-vars=RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}"
              ;;
            "generate_doc_summary_service")
              ENV_VARS="--set-env-vars=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"
              ;;
            "chat_service")
              ENV_VARS="--set-env-vars=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"
              ;;
            "get_download_url_service")
              ENV_VARS="--set-env-vars=GCS_BUCKET=${{ secrets.GCS_BUCKET }}"
              ;;
            *)
              ENV_VARS=""
              ;;
          esac
          
          echo "Deploying ${{ matrix.function_name }} to ${{ matrix.region }}"
          
          gcloud functions deploy ${{ matrix.function_name }} \
            --gen2 \
            --runtime=python311 \
            --project=$PROJECT_ID \
            --region=${{ matrix.region }} \
            --source=backend/${{ matrix.service }} \
            --entry-point=${{ matrix.entry_point }} \
            --trigger-http \
            --allow-unauthenticated \
            --service-account=${{ matrix.service_account }} \
            $ENV_VARS
      
      - name: Deploy Cloud Run Service
        if: matrix.type == 'run'
        run: |
          echo "Deploying ${{ matrix.service_name }} to ${{ matrix.region }}"
          
          gcloud run deploy ${{ matrix.service_name }} \
            --source=backend/${{ matrix.service }} \
            --project=$PROJECT_ID \
            --region=${{ matrix.region }} \
            --allow-unauthenticated \
            --service-account=${{ matrix.service_account }} \
            --port=8080 \
            --memory=2Gi \
            --cpu=1 \
            --timeout=300
      
      - name: Clean up service account key
        if: always() && matrix.service == 'get_download_url_service'
        run: |
          rm -f backend/get_download_url_service/service-account-key.json
      
      - name: Verify deployment
        run: |
          if [ "${{ matrix.type }}" = "function" ]; then
            echo "Verifying function deployment: ${{ matrix.function_name }}"
            gcloud functions describe ${{ matrix.function_name }} \
              --region=${{ matrix.region }} \
              --project=$PROJECT_ID \
              --format="value(name,status)"
          else
            echo "Verifying Cloud Run deployment: ${{ matrix.service_name }}"
            gcloud run services describe ${{ matrix.service_name }} \
              --region=${{ matrix.region }} \
              --project=$PROJECT_ID \
              --format="value(metadata.name,status.conditions[0].status)"
          fi

  notify:
    needs: [detect-changes, deploy]
    if: always() && needs.detect-changes.outputs.matrix != '[]' && needs.detect-changes.outputs.matrix != ''
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Summary
        run: |
          echo "Deployment completed!"
          echo "Project: ${{ secrets.GCLOUD_PROJECT_ID }}"
          echo "Notification email: ${{ secrets.NOTIFICATION_EMAIL }}"
          echo "Services deployed across 3 regions"